import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("public library keeps progressive disclosure and associates whole sets with curated subcategories", async () => {
  const source = await readFile(new URL("../src/CloudLibrary.tsx", import.meta.url), "utf8");
  const curated = await readFile(new URL("../src/CuratedLibrary.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../src/libraryProgressive.css", import.meta.url), "utf8");

  assert.match(source, /type LibraryView = "home" \| "curated" \| "sets"/);
  assert.match(source, /type SaveDestination = "sets" \| "curated" \| "both"/);
  assert.doesNotMatch(source, /CuratedSelectionMode/);
  assert.match(source, />Biblioteca curada</);
  assert.match(source, /view === "home"/);
  assert.match(source, /view === "curated" && <CuratedLibrary/);
  assert.match(source, /\["sets", "Meus conjuntos"\]/);
  assert.match(source, /\["curated", "Biblioteca curada"\]/);
  assert.match(source, /\["both", "Ambos"\]/);
  assert.match(source, /\+ Nova categoria/);
  assert.match(source, /\+ Nova subcategoria/);
  assert.match(source, /Subcategoria em/);
  assert.match(source, /selectCuratedCategory/);
  assert.match(source, /setCuratedSubcategoryId\(""\)/);
  assert.match(source, /subcategoryId/);
  assert.match(source, /replace/);
  assert.match(source, /já possui um conjunto associado/);
  assert.match(source, /Atualizar conjunto de/);
  assert.match(source, /Criar .* e adicionar conjunto/);
  assert.doesNotMatch(source, /Associar este conjunto à curadoria agora/);
  assert.match(source, /Remover da Biblioteca curada/);
  assert.match(source, /Excluir subcategoria vazia/);
  assert.match(source, /Excluir categoria vazia/);
  assert.match(source, /method: "DELETE"/);
  assert.doesNotMatch(source, /Selecionar hinos individualmente/);
  assert.doesNotMatch(source, /curated-hymn-selection/);
  assert.match(source, /publishBase\(name, slug, false\)/);
  assert.match(source, /conteúdo foi preservado em Meus conjuntos/);
  assert.match(curated, /hymnId: null/);
  assert.match(curated, /curated-set-link/);
  assert.doesNotMatch(curated, /Estudar agora|Compartilhar|curated-entry/);
  assert.match(styles, /\.library-entry-grid/);
  assert.match(styles, /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(styles, /\.save-destination/);
  assert.match(styles, /\.curation-create-context/);
  assert.match(styles, /\.curation-set-note/);
  assert.match(styles, /\.curated-set-link/);
  assert.doesNotMatch(styles, /\.curated-hymn-selection|\.curated-hymn-options/);
  assert.match(styles, /@media \(max-width:700px\)/);
  assert.match(styles, /\.curation-field-row,.curation-create-row \{ grid-template-columns:1fr;/);
});
